In [181]:
#BIKE STORE ANALYSIS

In [182]:
import pandas as pd
pd.set_option('display.max_colwidth', None)
import datetime as dt

In [183]:
#loading my retrieved SQL data in pandas f
example = pd.read_csv('Example Run (2).csv')
example

,first_name,city,email,customer_id,order_id,order_date,shipped_date,product_name,list_price,quantity,net_revenue,order_year,order_month
0,Ollie,Anaheim,ollie.zimmerman@yahoo.com,110,1252,2017-11-18 00:00:00,2017-11-21,Sun Bicycles Lil Kitt'n - 2017,109.99,1,87.99,2017,11
1,Thalia,Amityville,thalia.horne@yahoo.com,114,1472,2018-03-29 00:00:00,2018-03-31,Sun Bicycles Lil Kitt'n - 2017,109.99,1,87.99,2018,3
2,Collen,San Pablo,collen.dennis@gmail.com,1097,690,2017-02-03 00:00:00,2017-02-06,Sun Bicycles Lil Kitt'n - 2017,109.99,1,87.99,2017,2
3,Andria,Amarillo,andria.rivers@aol.com,730,1210,2017-10-26 00:00:00,2017-10-29,Sun Bicycles Lil Kitt'n - 2017,109.99,1,98.99,2017,10
4,Klara,Rome,klara.kim@gmail.com,858,667,2017-01-22 00:00:00,2017-01-25,Sun Bicycles Lil Kitt'n - 2017,109.99,1,98.99,2017,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3902,Melanie,Liverpool,melanie.hayes@msn.com,73,937,2017-06-11 00:00:00,2017-06-13,Trek Silque SLR 8 Women's - 2017,6499.99,2,12089.98,2017,6
3903,Delmar,Lockport,delmar.wise@yahoo.com,908,672,2017-01-26 00:00:00,2017-01-29,Trek Silque SLR 8 Women's - 2017,6499.99,2,12089.98,2017,1
3904,Dorothea,Astoria,dorothea.chang@gmail.com,692,1463,2018-03-23 00:00:00,2018-03-24,Trek Silque SLR 8 Women's - 2017,6499.99,2,12349.98,2018,3
3905,Shae,Floral Park,shae.hickman@hotmail.com,108,1297,2017-12-14 00:00:00,2017-12-16,Trek Silque SLR 8 Women's - 2017,6499.99,2,12349.98,2017,12
3906,Marlo,Niagara Falls,marlo.jefferson@gmail.com,503,1003,2017-07-14 00:00:00,2017-07-16,Trek Silque SLR 8 Women's - 2017,6499.99,2,12349.98,2017,7

In [184]:
# 1. Ensure order_date is a datetime object
example['order_date'] = pd.to_datetime(example['order_date'])
example

,first_name,city,email,customer_id,order_id,order_date,shipped_date,product_name,list_price,quantity,net_revenue,order_year,order_month
0,Ollie,Anaheim,ollie.zimmerman@yahoo.com,110,1252,2017-11-18,2017-11-21,Sun Bicycles Lil Kitt'n - 2017,109.99,1,87.99,2017,11
1,Thalia,Amityville,thalia.horne@yahoo.com,114,1472,2018-03-29,2018-03-31,Sun Bicycles Lil Kitt'n - 2017,109.99,1,87.99,2018,3
2,Collen,San Pablo,collen.dennis@gmail.com,1097,690,2017-02-03,2017-02-06,Sun Bicycles Lil Kitt'n - 2017,109.99,1,87.99,2017,2
3,Andria,Amarillo,andria.rivers@aol.com,730,1210,2017-10-26,2017-10-29,Sun Bicycles Lil Kitt'n - 2017,109.99,1,98.99,2017,10
4,Klara,Rome,klara.kim@gmail.com,858,667,2017-01-22,2017-01-25,Sun Bicycles Lil Kitt'n - 2017,109.99,1,98.99,2017,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3902,Melanie,Liverpool,melanie.hayes@msn.com,73,937,2017-06-11,2017-06-13,Trek Silque SLR 8 Women's - 2017,6499.99,2,12089.98,2017,6
3903,Delmar,Lockport,delmar.wise@yahoo.com,908,672,2017-01-26,2017-01-29,Trek Silque SLR 8 Women's - 2017,6499.99,2,12089.98,2017,1
3904,Dorothea,Astoria,dorothea.chang@gmail.com,692,1463,2018-03-23,2018-03-24,Trek Silque SLR 8 Women's - 2017,6499.99,2,12349.98,2018,3
3905,Shae,Floral Park,shae.hickman@hotmail.com,108,1297,2017-12-14,2017-12-16,Trek Silque SLR 8 Women's - 2017,6499.99,2,12349.98,2017,12
3906,Marlo,Niagara Falls,marlo.jefferson@gmail.com,503,1003,2017-07-14,2017-07-16,Trek Silque SLR 8 Women's - 2017,6499.99,2,12349.98,2017,7

In [185]:
#checking my data for missing values
#checking email for missing values
example.info()
example['email'].isna().any()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3907 entries, 0 to 3906
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   first_name    3907 non-null   object
 1   city          3907 non-null   object
 2   email         3907 non-null   object
 3   customer_id   3907 non-null   int64
 4   order_id      3907 non-null   int64
 5   order_date    3907 non-null   datetime64[ns]
 6   shipped_date  3907 non-null   object
 7   product_name  3907 non-null   object
 8   list_price    3907 non-null   float64
 9   quantity      3907 non-null   int64
 10  net_revenue   3907 non-null   float64
 11  order_year    3907 non-null   int64
 12  order_month   3907 non-null   int64
dtypes: datetime64[ns](1), float64(2), int64(5), object(5)
memory usage: 396.9+ KB

np.False_

In [186]:
#assigned a new column called cost price to my dataset based on a percentage of the list price
example['cost_price'] = (example['list_price'] * 0.6).round(2)
example.head()

,first_name,city,email,customer_id,order_id,order_date,shipped_date,product_name,list_price,quantity,net_revenue,order_year,order_month,cost_price
0,Ollie,Anaheim,ollie.zimmerman@yahoo.com,110,1252,2017-11-18,2017-11-21,Sun Bicycles Lil Kitt'n - 2017,109.99,1,87.99,2017,11,65.99
1,Thalia,Amityville,thalia.horne@yahoo.com,114,1472,2018-03-29,2018-03-31,Sun Bicycles Lil Kitt'n - 2017,109.99,1,87.99,2018,3,65.99
2,Collen,San Pablo,collen.dennis@gmail.com,1097,690,2017-02-03,2017-02-06,Sun Bicycles Lil Kitt'n - 2017,109.99,1,87.99,2017,2,65.99
3,Andria,Amarillo,andria.rivers@aol.com,730,1210,2017-10-26,2017-10-29,Sun Bicycles Lil Kitt'n - 2017,109.99,1,98.99,2017,10,65.99
4,Klara,Rome,klara.kim@gmail.com,858,667,2017-01-22,2017-01-25,Sun Bicycles Lil Kitt'n - 2017,109.99,1,98.99,2017,1,65.99

In [187]:
#calculating profit
example['profit'] = example['net_revenue'] - (example['cost_price'] * example['quantity']).round(2)
example

,first_name,city,email,customer_id,order_id,order_date,shipped_date,product_name,list_price,quantity,net_revenue,order_year,order_month,cost_price,profit
0,Ollie,Anaheim,ollie.zimmerman@yahoo.com,110,1252,2017-11-18,2017-11-21,Sun Bicycles Lil Kitt'n - 2017,109.99,1,87.99,2017,11,65.99,22.0
1,Thalia,Amityville,thalia.horne@yahoo.com,114,1472,2018-03-29,2018-03-31,Sun Bicycles Lil Kitt'n - 2017,109.99,1,87.99,2018,3,65.99,22.0
2,Collen,San Pablo,collen.dennis@gmail.com,1097,690,2017-02-03,2017-02-06,Sun Bicycles Lil Kitt'n - 2017,109.99,1,87.99,2017,2,65.99,22.0
3,Andria,Amarillo,andria.rivers@aol.com,730,1210,2017-10-26,2017-10-29,Sun Bicycles Lil Kitt'n - 2017,109.99,1,98.99,2017,10,65.99,33.0
4,Klara,Rome,klara.kim@gmail.com,858,667,2017-01-22,2017-01-25,Sun Bicycles Lil Kitt'n - 2017,109.99,1,98.99,2017,1,65.99,33.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3902,Melanie,Liverpool,melanie.hayes@msn.com,73,937,2017-06-11,2017-06-13,Trek Silque SLR 8 Women's - 2017,6499.99,2,12089.98,2017,6,3899.99,4290.0
3903,Delmar,Lockport,delmar.wise@yahoo.com,908,672,2017-01-26,2017-01-29,Trek Silque SLR 8 Women's - 2017,6499.99,2,12089.98,2017,1,3899.99,4290.0
3904,Dorothea,Astoria,dorothea.chang@gmail.com,692,1463,2018-03-23,2018-03-24,Trek Silque SLR 8 Women's - 2017,6499.99,2,12349.98,2018,3,3899.99,4550.0
3905,Shae,Floral Park,shae.hickman@hotmail.com,108,1297,2017-12-14,2017-12-16,Trek Silque SLR 8 Women's - 2017,6499.99,2,12349.98,2017,12,3899.99,4550.0
3906,Marlo,Niagara Falls,marlo.jefferson@gmail.com,503,1003,2017-07-14,2017-07-16,Trek Silque SLR 8 Women's - 2017,6499.99,2,12349.98,2017,7,3899.99,4550.0

In [188]:
#calculating profit margin 
example['profit_margin'] = (example['profit'] / example['net_revenue'] * 100).round(2)
example

,first_name,city,email,customer_id,order_id,order_date,shipped_date,product_name,list_price,quantity,net_revenue,order_year,order_month,cost_price,profit,profit_margin
0,Ollie,Anaheim,ollie.zimmerman@yahoo.com,110,1252,2017-11-18,2017-11-21,Sun Bicycles Lil Kitt'n - 2017,109.99,1,87.99,2017,11,65.99,22.0,25.00
1,Thalia,Amityville,thalia.horne@yahoo.com,114,1472,2018-03-29,2018-03-31,Sun Bicycles Lil Kitt'n - 2017,109.99,1,87.99,2018,3,65.99,22.0,25.00
2,Collen,San Pablo,collen.dennis@gmail.com,1097,690,2017-02-03,2017-02-06,Sun Bicycles Lil Kitt'n - 2017,109.99,1,87.99,2017,2,65.99,22.0,25.00
3,Andria,Amarillo,andria.rivers@aol.com,730,1210,2017-10-26,2017-10-29,Sun Bicycles Lil Kitt'n - 2017,109.99,1,98.99,2017,10,65.99,33.0,33.34
4,Klara,Rome,klara.kim@gmail.com,858,667,2017-01-22,2017-01-25,Sun Bicycles Lil Kitt'n - 2017,109.99,1,98.99,2017,1,65.99,33.0,33.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3902,Melanie,Liverpool,melanie.hayes@msn.com,73,937,2017-06-11,2017-06-13,Trek Silque SLR 8 Women's - 2017,6499.99,2,12089.98,2017,6,3899.99,4290.0,35.48
3903,Delmar,Lockport,delmar.wise@yahoo.com,908,672,2017-01-26,2017-01-29,Trek Silque SLR 8 Women's - 2017,6499.99,2,12089.98,2017,1,3899.99,4290.0,35.48
3904,Dorothea,Astoria,dorothea.chang@gmail.com,692,1463,2018-03-23,2018-03-24,Trek Silque SLR 8 Women's - 2017,6499.99,2,12349.98,2018,3,3899.99,4550.0,36.84
3905,Shae,Floral Park,shae.hickman@hotmail.com,108,1297,2017-12-14,2017-12-16,Trek Silque SLR 8 Women's - 2017,6499.99,2,12349.98,2017,12,3899.99,4550.0,36.84
3906,Marlo,Niagara Falls,marlo.jefferson@gmail.com,503,1003,2017-07-14,2017-07-16,Trek Silque SLR 8 Women's - 2017,6499.99,2,12349.98,2017,7,3899.99,4550.0,36.84

In [189]:
# .size() counts the rows, .reset_index() turns it back into a DataFrame
counts_df = example.groupby(['email', 'product_name']).size().reset_index(name='count')

# Sort it so the duplicates are obvious
counts_df = counts_df.sort_values(by='count', ascending=False)
counts_df

,email,product_name,count
983,denis.logan@msn.com,Electra Girl's Hawaii 1 (16-inch) - 2015/2016,2
1759,joesph.delacruz@aol.com,Electra Girl's Hawaii 1 (16-inch) - 2015/2016,2
211,anisha.lang@aol.com,Electra Townie Original 21D - 2016,2
844,cris.dunn@yahoo.com,Electra Girl's Hawaii 1 (16-inch) - 2015/2016,2
320,ayanna.rhodes@msn.com,Electra Cruiser 1 (24-Inch) - 2016,2
...,...,...,...
14,adam.henderson@hotmail.com,Electra Townie Original 7D - 2017,1
15,adam.henderson@hotmail.com,Trek Boone 7 - 2017,1
16,adam.thornton@hotmail.com,Surly Straggler - 2016,1
17,adam.thornton@hotmail.com,Surly Wednesday Frameset - 2016,1
18,adam.thornton@hotmail.com,Trek Remedy 29 Carbon Frameset - 2016,1

In [190]:
# This shows all the repeated rows
duplicates = example[example.duplicated(subset=['email', 'product_name', 'quantity', 'list_price'], keep=False)]
duplicates.sort_values(by=['email', 'product_name']).head()

,first_name,city,email,customer_id,order_id,order_date,shipped_date,product_name,list_price,quantity,net_revenue,order_year,order_month,cost_price,profit,profit_margin
1485,Beatris,Spring Valley,beatris.joyner@gmail.com,1169,551,2016-11-12,2016-11-13,Electra Townie Original 7D EQ - 2016,599.99,1,557.99,2016,11,359.99,198.0,35.48
1539,Beatris,Spring Valley,beatris.joyner@gmail.com,1169,551,2016-11-12,2016-11-13,Electra Townie Original 7D EQ - 2016,599.99,1,569.99,2016,11,359.99,210.0,36.84
199,Cira,Oakland,cira.downs@gmail.com,759,536,2016-10-31,2016-11-01,Electra Girl's Hawaii 1 (16-inch) - 2015/2016,269.99,1,242.99,2016,10,161.99,81.0,33.33
240,Cira,Oakland,cira.downs@gmail.com,759,536,2016-10-31,2016-11-01,Electra Girl's Hawaii 1 (16-inch) - 2015/2016,269.99,1,251.09,2016,10,161.99,89.1,35.49
2294,Etsuko,Richmond Hill,etsuko.garrison@yahoo.com,667,442,2016-09-18,2016-09-21,Electra Townie Original 7D EQ - 2016,599.99,2,959.98,2016,9,359.99,240.0,25.00

In [191]:
# Segment customers based on order frequency:
# - 'New': Exactly 1 order
# - 'Loyal': More than 3 orders
# - 'Repeat': Everything in between (2-3 orders)
def segment_customer(row):
    if row['quantity'] == 1:
        return 'New'
    elif row['quantity'] > 3:
        return 'Loyal'
    else:
        return 'Regular'

example['Customer Segment'] = example.apply(segment_customer, axis=1)

In [192]:
example.head()

,first_name,city,email,customer_id,order_id,order_date,shipped_date,product_name,list_price,quantity,net_revenue,order_year,order_month,cost_price,profit,profit_margin,Customer Segment
0,Ollie,Anaheim,ollie.zimmerman@yahoo.com,110,1252,2017-11-18,2017-11-21,Sun Bicycles Lil Kitt'n - 2017,109.99,1,87.99,2017,11,65.99,22.0,25.00,New
1,Thalia,Amityville,thalia.horne@yahoo.com,114,1472,2018-03-29,2018-03-31,Sun Bicycles Lil Kitt'n - 2017,109.99,1,87.99,2018,3,65.99,22.0,25.00,New
2,Collen,San Pablo,collen.dennis@gmail.com,1097,690,2017-02-03,2017-02-06,Sun Bicycles Lil Kitt'n - 2017,109.99,1,87.99,2017,2,65.99,22.0,25.00,New
3,Andria,Amarillo,andria.rivers@aol.com,730,1210,2017-10-26,2017-10-29,Sun Bicycles Lil Kitt'n - 2017,109.99,1,98.99,2017,10,65.99,33.0,33.34,New
4,Klara,Rome,klara.kim@gmail.com,858,667,2017-01-22,2017-01-25,Sun Bicycles Lil Kitt'n - 2017,109.99,1,98.99,2017,1,65.99,33.0,33.34,New

In [193]:
# 1. Group by city to get total revenue and total unique orders
region_stats = example.groupby('city').agg({
    'net_revenue': 'sum',
    'order_id': 'nunique'
})

region_stats

                  net_revenue  order_id
city
Albany               15280.31         3
Amarillo              9573.63         5
Amityville           34124.44         9
Amsterdam            20441.66         5
Anaheim              27688.33        11
...                       ...       ...
Woodhaven            40201.58         8
Woodside             27833.58        10
Yonkers              16975.48         6
Yorktown Heights      9763.20         5
Yuba City              322.99         1

[195 rows x 2 columns]

In [194]:
# 2. Calculate Average Order Value for each city
region_stats['AOV'] = region_stats['net_revenue'] / region_stats['order_id']
region_stats['AOV']

city
Albany              5093.436667
Amarillo            1914.726000
Amityville          3791.604444
Amsterdam           4088.332000
Anaheim             2517.120909
                       ...
Woodhaven           5025.197500
Woodside            2783.358000
Yonkers             2829.246667
Yorktown Heights    1952.640000
Yuba City            322.990000
Name: AOV, Length: 195, dtype: float64

In [195]:
# 3. Use .describe() to see the "Big Picture" of your AOV across all cities
print("Statistical Summary of Regional AOV:")
print(region_stats['AOV'].describe())

Statistical Summary of Regional AOV:
count      195.000000
mean      4201.193088
std       1579.208061
min        322.990000
25%       3178.676806
50%       4034.838750
75%       5132.570972
max      10981.402857
Name: AOV, dtype: float64

In [196]:
# 4. Show the top 5 cities with the highest AOV
print("\nCities with Highest Average Order Value:")
print(region_stats['AOV'].sort_values(ascending=False).head(5))

Cities with Highest Average Order Value:
city
Harlingen             10981.402857
Oakland Gardens        9773.880000
New Rochelle           7700.024286
Huntington Station     7211.631250
Baldwinsville          7073.186667
Name: AOV, dtype: float64

In [197]:
# 2. Create a Month-Year column for grouping
example['month_year'] = example['order_date'].dt.to_period('M')

In [198]:
example['month_year']

0       2017-11
1       2018-03
2       2017-02
3       2017-10
4       2017-01
         ...
3902    2017-06
3903    2017-01
3904    2018-03
3905    2017-12
3906    2017-07
Name: month_year, Length: 3907, dtype: period[M]

In [199]:
# 3. Group by product and month to see revenue trends
monthly_sales = example.groupby(['product_name', 'month_year'])['net_revenue'].sum().unstack()

In [200]:
monthly_sales

month_year,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,...,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03
product_name,,,,,,,,,,,,,,,,,,,,,
Electra Amsterdam Fashion 7i Ladies' - 2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3805.96,3959.96,2969.97,2045.98,5829.94,1979.98,4971.95,NaN,2089.98,2089.98
Electra Amsterdam Original 3i - 2015/2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4157.93,1821.57,1854.57,1187.98,NaN,1141.78,1240.78,NaN,NaN,2309.96
Electra Amsterdam Original 3i Ladies' - 2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1669.77,1055.98,527.99,1141.78,527.99,626.99,1649.97,626.99,613.79,NaN
Electra Cruiser 1 (24-Inch) - 2016,5100.09,4579.01,3202.07,3399.16,3841.94,4168.63,4063.33,6630.93,5748.07,8056.47,...,1406.64,472.48,1773.83,1241.95,1757.63,494.08,NaN,1433.64,NaN,NaN
Electra Cruiser Lux 1 - 2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1913.95,818.38,1566.36,NaN,805.18,417.99,1253.97,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Trek Silque SLR 7 Women's - 2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16799.97,NaN,17099.97,16739.97,5579.99,11159.98,9599.98,NaN,NaN,11159.98
Trek Silque SLR 8 Women's - 2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,29639.95,24049.96,6174.99,17549.97,12219.98,11894.98,12349.98,NaN,NaN,12349.98
Trek Slash 8 27.5 - 2016,42999.88,18479.95,23999.93,33279.91,47119.87,59719.84,37079.90,40559.88,55039.85,18839.95,...,3599.99,11239.97,11119.97,10799.97,10639.97,10519.97,3599.99,3719.99,3799.99,7439.98
Trek Stache 5 - 2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1394.99,1349.99,NaN,5549.96,2849.98,NaN,NaN,NaN,2699.98,2849.98
Trek X-Caliber 8 - 2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1859.98,2799.97,3499.96,1899.98,4499.95,1599.98,NaN,1599.98,NaN,799.99

In [201]:
# 4. Calculate percentage growth between the last two available months
growth = (monthly_sales.iloc[:, -1] - monthly_sales.iloc[:, -2]) / monthly_sales.iloc[:, -2] * 100
growth

product_name
Electra Amsterdam Fashion 7i Ladies' - 2017      0.000000
Electra Amsterdam Original 3i - 2015/2017             NaN
Electra Amsterdam Original 3i Ladies' - 2017          NaN
Electra Cruiser 1 (24-Inch) - 2016                    NaN
Electra Cruiser Lux 1 - 2017                          NaN
                                                  ...
Trek Silque SLR 7 Women's - 2017                      NaN
Trek Silque SLR 8 Women's - 2017                      NaN
Trek Slash 8 27.5 - 2016                        95.789463
Trek Stache 5 - 2017                             5.555597
Trek X-Caliber 8 - 2017                               NaN
Length: 102, dtype: float64

In [202]:
# 5. Find the top growing product
print("Top 5 Fastest Growing Products (%):")
print(growth.sort_values(ascending=False).head(5))

Top 5 Fastest Growing Products (%):
product_name
Haro Shredder 20 - 2017           104.301296
Trek Precaliber 16 Boys - 2017    100.000000
Trek Slash 8 27.5 - 2016           95.789463
Sun Bicycles Drifter 7 - 2017      93.548240
Surly Ogre Frameset - 2017         16.250271
dtype: float64

In [203]:
#cleaned data
example.to_csv('extremelycleaned_data.csv', index = False)